// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldxeehahwawrsrxzigoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkeGVlaGFod2F3cnNyeHppZ29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzg3MDEsImV4cCI6MjA2NjY1NDcwMX0.g4qAWyrkU6qGNXx1N6jQGOMPKvp1sL-PwLWN6a0qDzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});